version: '3'
services:
  web:
    build: .
    ports:
     - "3000:80"
    depends_on:
      - server
    links:
      - server
  server:
    build: ./server
    ports:
     - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000